[package]
name = "ctrlassist"
version = "0.4.0"
authors = ["ruffsl <roxfoxpox@gmail.com>"]
edition = "2024"
rust-version = "1.91.1"
description = "Controller Assist for gaming on Linux"
documentation = "https://docs.rs/ctrlassist/"
readme = "README.md"
homepage = "https://github.com/ruffsl/CtrlAssist"
repository = "https://github.com/ruffsl/CtrlAssist"
license = "Apache-2.0"
keywords = [
    "gamepad",
    "input",
    "joystick",
]
categories = ["game-engines"]
exclude = [
    ".envrc",
    ".github/",
    ".vscode/",
    "docs/",
    "flake.*",
    "flatpak/",
    "rust-toolchain.toml",
]

[badges]
github = { repository = "ruffsl/CtrlAssist" }

[dependencies]
clap = { version = "^4.5", features = ["derive"] }
dirs = "6"
env_logger = "0.11"
evdev = "0.13"
fs2 = "0.4"
gilrs = "^0.11.1"
libc = "0.2"
log = "0.4"
signal-hook = "0.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
udev = "0.9"
uuid = "1"


# New dependencies for tray
ashpd = "0.12"
futures = "0.3"
futures-util = "0.3"
ksni = "^0.3.3"
notify-rust = "4.11"
parking_lot = "0.12"
serde = "1"
toml = "0.9"

[package.metadata.deb]
depends = "libudev1"
section = "utils"

# [profile.release]
# codegen-units = 1
# lto = true
# opt-level = "z"
# strip = true
